# Generated by Django 5.2.2 on 2025-08-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='portfolio',
            new_name='portf',
        ),
    ]
